apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: default
type: Opaque
data:
  # Replace the placeholders with base64-encoded values before applying in GitOps.
  N8N_BASIC_AUTH_USER: REPLACE_BASE64_ADMIN_USER
  N8N_BASIC_AUTH_PASSWORD: REPLACE_BASE64_ADMIN_PASSWORD
